accounts/urls.py
from django.urls import path
from .views import *
from . import views
from django.contrib.auth import  views as auth_views


app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', user_registration, name='register'),
    path('complete_profile/',complete_profile,name='complete_profile'),
    path('address_details/',address_details,name='address_details'),
    path('employment_details/',employment_details,name='employment_details'),
    path('educational_details/',educational_details.as_view(),name='educational_details'),
    path('about_details/',about_details,name='about_details'),
    path('relation/',relation.as_view(),name='relation'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile_edit/',ProfileUpdateView.as_view(),name ='profile_edit'),
    path('address_edit/',AddressUpdateView.as_view(),name ='address_edit'),
    path('employ_edit/',EmploymentUpdateView.as_view(),name ='employ_edit'),
    path('additional_edit/',AdditionalUpdateView.as_view(),name ='additional_edit'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('delete-account/', delete_account_view, name='delete_account'),
    path('password_reset/', custom_password_reset_request, name='custom_password_reset_request'),
    path('reset/<uidb64>/<token>/', custom_password_reset_confirm, name='custom_password_reset_confirm'),
]

app/urls.py
from django.contrib import admin
from django.urls import path,include,reverse
from .views import *

from . import views



app_name = 'app'
urlpatterns = [
    path('index/',views.index,name='index'),
    
    path('dashboard/',views.dashboard,name='dashboard'),
    path('usermanage/',views.usermanage,name='usermanage'),
    path('billing/',views.billing,name='billing'),
    path('adminprofile/',views.adminprofile,name='adminprofile'),
    path('contentmanage/',views.contentmanage,name='contentmanage'),
   
    # path('userlogin/',views.userlogin,name='userlogin'),
   
   
    path('support/',views.support,name='support'),
    
    
   
   
   
    
    path('family_details/',family_details,name='family_details'),
    path('partner/',partner,name='partner'),
   
    
    path('', HomeView.as_view(), name='home'),
    path('pview/', pview.as_view(), name='pview'),
    path('notification/',notification.as_view(),name='notification'),
    path('list_profiles/', ProfileListView.as_view(), name='list_profiles'),
    path('detailed_profile/<int:id>/', detailed_profile, name='detailed_profile'),
    path('change_profile/', change_profile_picture, name='change_profile'),
    path('upload_files/', upload_files, name='upload_files'),
    path('send_friend_request/<int:user_id>/', views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('delete_friend_request/<int:request_id>/', views.delete_friend_request, name='delete_friend_request'),
    path('unfriend/<int:user_id>/', unfriend, name='unfriend'),
    path('received_requests/', views.received_requests, name='received_requests'),
    path('shortlist/<int:user_id>/', shortlist_profile, name='shortlist_profile'),
    path('favorites/', favorite_profiles, name='favorite_profiles'),
    path('remove_from_favorites/<int:profile_id>/', remove_from_favorites, name='remove_from_favorites'),
    
    path('chat/<int:id>/', views.messaging_page, name='messaging_page'),
    path('send_message/', views.send_message, name='send_message'),
    path('get_messages/<int:id>/', views.get_messages, name='get_messages'),
    path('not_premium/',not_premium,name='not_premium'),
    
    
    
    
    
    
    
    
   
]

matrimony/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    # path("admin/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('payment/', include('payment.urls', namespace='payment')), 
    path('', include('app.urls', namespace='app')),
]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

payment/urls.py
from django.urls import path
from .views import *
from . import views
from django.contrib.auth import  views as auth_views


app_name = 'accounts'
urlpatterns = [
    path('pay/<int:plan_id>/', PaymentView.as_view(), name='payment'),
    path('payment_success/', payment_success, name='payment_success'),
    path('payment_error/<int:plan_id>/', payment_error, name='payment_error'),
    path('plans/', plan_list, name='plan_list'),
]

templates/shared/base.html
<!doctype html>
<html lang="en">

<head>
    
    {% block meta %}
        
    {% endblock meta %}
    
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS v5.2.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />

    {% block styles %}
        
    {% endblock styles %}
        
</head>

<body>
    <header>
        {% include 'shared/navbar.html' %}
    </header>
    <main>
       
    
        {% block content %}
            
        {% endblock content %}
            
    </main>
    <footer>
        <!-- place footer here -->
    </footer>
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    
    {% block scripts %}
        
    {% endblock scripts %}
        
</body>

</html>

templates/shared/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/navbar.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand text-light" href="{% url 'app:list_profiles' %}">Matrimony</a>
    <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse"
            data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="collapsibleNavId">
        <ul class="navbar-nav mx-auto d-flex justify-content-center">
            {% if user.is_authenticated %}
            <li class="nav-item mx-2">
                <a class="nav-link text-light {% if request.resolver_match.url_name == 'list_profiles' %}active{% endif %}" href="{% url 'app:list_profiles' %}">Matches</a>
            </li>
            <li class="nav-item mx-2">
                <a class="nav-link text-light {% if request.resolver_match.url_name == 'messaging_page' %}active{% endif %}" href="{% url 'app:messaging_page' 1 %}">Messages</a>
            </li>
            <li class="nav-item mx-2">
                <a class="nav-link text-light {% if request.resolver_match.url_name == 'favorite_profiles' %}active{% endif %}" href="{% url 'app:favorite_profiles' %}">Favorites</a>
            </li>
            <li class="nav-item mx-2">
                <a class="nav-link text-light {% if request.resolver_match.url_name == 'received_requests' %}active{% endif %}" href="{% url 'app:received_requests' %}">Requests</a>
            </li>
            {% endif %}

            {% if not user.is_authenticated %}
            <li class="nav-item mx-2">
                <a class="nav-link text-light {% if request.resolver_match.url_name == '' %}active{% endif %}" href="{% url 'app:home'%}">Home</a>
            </li>
            <li class="nav-item mx-2">
                <a class="nav-link text-light {% if request.resolver_match.url_name == '' %}active{% endif %}" href="#">Contact</a>
            </li>
            <li class="nav-item mx-2">
                <a class="nav-link text-light {% if request.resolver_match.url_name == 'login' %}active{% endif %}" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item mx-2">
                <a class="nav-link text-light {% if request.resolver_match.url_name == 'register' %}active{% endif %}" href="{% url 'accounts:register' %}">Register</a>
            </li>
            {% endif %}
        </ul>

        <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}
            <li class="nav-item mx-2">
                <a class="nav-link text-light {% if request.resolver_match.url_name == 'notification' %}active{% endif %}" href="{% url 'app:notification' %}" role="button" aria-expanded="false">
                    <i class="fas fa-bell"></i>
                </a>
            </li>
            <li class="nav-item dropdown mx-2">
                <a class="nav-link dropdown-toggle text-light {% if request.resolver_match.url_name == 'profile' %}active{% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fas fa-user"></i>
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change Password</a></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:delete_account' %}">Delete Account</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'payment:plan_list' %}">Try Premium</a></a></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                </ul>
            </li>
            <li class="nav-item mx-2">
                <a class="nav-link text-light try-premium-link" href="{% url 'payment:plan_list' %}">
                    <i class="fas fa-star premium-icon"></i> Try Premium
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
</body>
</html>