accounts/urls.py
from django.urls import path
from .views import *
from . import views
from django.contrib.auth import  views as auth_views


app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', user_registration, name='register'),
    path('complete_profile/',complete_profile,name='complete_profile'),
    path('address_details/',address_details,name='address_details'),
    path('employment_details/',employment_details,name='employment_details'),
    path('educational_details/',educational_details.as_view(),name='educational_details'),
    path('about_details/',about_details,name='about_details'),
    path('relation/',relation.as_view(),name='relation'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile_edit/',ProfileUpdateView.as_view(),name ='profile_edit'),
    path('address_edit/',AddressUpdateView.as_view(),name ='address_edit'),
    path('employ_edit/',EmploymentUpdateView.as_view(),name ='employ_edit'),
    path('additional_edit/',AdditionalUpdateView.as_view(),name ='additional_edit'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('delete-account/', delete_account_view, name='delete_account'),
    path('password_reset/', custom_password_reset_request, name='custom_password_reset_request'),
    path('reset/<uidb64>/<token>/', custom_password_reset_confirm, name='custom_password_reset_confirm'),
]

app/urls.py
from django.contrib import admin
from django.urls import path,include,reverse
from .views import *

from . import views



app_name = 'app'
urlpatterns = [
    path('index/',views.index,name='index'),
    
    path('dashboard/',views.dashboard,name='dashboard'),
    path('usermanage/',views.usermanage,name='usermanage'),
    path('billing/',views.billing,name='billing'),
    path('adminprofile/',views.adminprofile,name='adminprofile'),
    path('contentmanage/',views.contentmanage,name='contentmanage'),
   
    # path('userlogin/',views.userlogin,name='userlogin'),
   
   
    path('support/',views.support,name='support'),
    
    
   
   
   
    
    path('family_details/',family_details,name='family_details'),
    path('partner/',partner,name='partner'),
   
    
    path('', HomeView.as_view(), name='home'),
    path('pview/', pview.as_view(), name='pview'),
    path('notification/',notification.as_view(),name='notification'),
    path('list_profiles/', ProfileListView.as_view(), name='list_profiles'),
    path('detailed_profile/<int:id>/', detailed_profile, name='detailed_profile'),
    path('change_profile/', change_profile_picture, name='change_profile'),
    path('upload_files/', upload_files, name='upload_files'),
    path('send_friend_request/<int:user_id>/', views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('delete_friend_request/<int:request_id>/', views.delete_friend_request, name='delete_friend_request'),
    path('unfriend/<int:user_id>/', unfriend, name='unfriend'),
    path('received_requests/', views.received_requests, name='received_requests'),
    path('shortlist/<int:user_id>/', shortlist_profile, name='shortlist_profile'),
    path('favorites/', favorite_profiles, name='favorite_profiles'),
    path('remove_from_favorites/<int:profile_id>/', remove_from_favorites, name='remove_from_favorites'),
    
    path('chat/<int:id>/', views.messaging_page, name='messaging_page'),
    path('send_message/', views.send_message, name='send_message'),
    path('get_messages/<int:id>/', views.get_messages, name='get_messages'),
    path('not_premium/',not_premium,name='not_premium'),
    
    
    
    
    
    
    
    
   
]

matrimony/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    # path("admin/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('payment/', include('payment.urls', namespace='payment')), 
    path('', include('app.urls', namespace='app')),
]
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

templates/user/chat.html
{% extends 'shared/base.html' %}

{% block content %}
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sample Messaging Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'assets/css/usercss/chat.css' %}">
</head>
<body>
    <div class="container mt-4">
        <div class="header">
            <h2 >Messaging {% if unread_messages %}<span class="badge badge-danger">New</span>{% endif %}</h2>
        </div>
        
        <div class="chat-container">
            <div class="container-box user-list-container">
                <div class="user-list">
                    <h5 class="align-items-center">Users</h5>
                    <ul class="list-group">
                        {% for user in users %}
                            <li class="list-group-item user-list-item {% if user.id == receiver.id %}active{% endif %}">
                                {% if user.profile_photo %}
                                <img src="{{ user.profile_photo.url }}" alt="{{ user.username }}'s profile picture">
                                {% endif %}
                                <a href="{% url 'app:messaging_page' user.id %}"><b>{{ user.first_name }} {{ user.last_name}}</b></a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            {% if user_id %}
            <div class="container-box message-section">
                <div class="message-header">
                    {% if receiver.profile_photo %}
                    <img src="{{ receiver.profile_photo.url }}" alt="{{ receiver.first_name }}'s profile picture" class="profile-photo">
                    {% endif %}
                    <h4>{{ receiver.first_name }} {{ receiver.last_name }}</h4>
                    <div class="call-icons">
                        <a href="#"><i class="fas fa-phone-alt fa-lg mr-3"></i></a>
                        <a href="#"><i class="fas fa-video fa-lg"></i></a>
                    </div>
                </div>

                <div class="message-list" id="chat-window">
                </div>
                <div class="message-form">
                    <form id="message-form">
                        <textarea id="message-input" class="form-control" rows="3" placeholder="Type your message..."></textarea>
                        <button type="submit" class="send-button" id="send-button"  {% if not is_friend %}disabled{% endif %}>
                            Send
                        </button>
                        {% if not is_friend %}
                        <small class="text-danger">You cannot send messages to this user until you become friends.</small>
                        {% endif %}
                        
                    </form>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const chatWindow = document.getElementById('chat-window');
            const messageForm = document.getElementById('message-form');
            const messageInput = document.getElementById('message-input');
            const userId = "{{ user_id }}";
            const csrfToken = "{{ csrf_token }}";

            function sendMessage(event) {
                event.preventDefault();
                const messageContent = messageInput.value.trim();

                if (messageContent === '') {
                    return;
                }

                fetch("{% url 'app:send_message' %}", {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrfToken
                    },
                    body: JSON.stringify({ content: messageContent, receiver_id: userId })
                })
                .then(response => response.json())
                .then(data => {
                    console.log('Message sent:', data);
                    messageInput.value = '';
                    loadMessages();
                })
                .catch(error => {
                    console.error('Error sending message:', error);
                });
            }

            function loadMessages() {
                fetch(`/get_messages/${userId}/`)
                    .then(response => response.json())
                    .then(data => {
                        chatWindow.innerHTML = '';
                        data.messages.forEach(message => {
                            const messageElement = document.createElement('div');
                            messageElement.classList.add('message');
                            messageElement.classList.add(message.sender === '{{ request.user.username }}' ? 'sent' : 'received');
                            messageElement.innerHTML = `<p> ${message.content}<span class="timestamp">${message.timestamp}</span></p>`;
                            if (message.status === 'read') {
                                messageElement.innerHTML += `<span class="message-status">${message.status}</span>`;
                            } else if (message.status === 'delivered') {
                                messageElement.innerHTML += `<span class="message-status">${message.status}</span>`;
                            }
                            chatWindow.appendChild(messageElement);
                        });
                        chatWindow.scrollTop = chatWindow.scrollHeight;
                    })
                    .catch(error => {
                        console.error('Error fetching messages:', error);
                    });
            }

            messageForm.addEventListener('submit', sendMessage);
            loadMessages();
            setInterval(loadMessages, 5000);
        });
    </script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
{% endblock content %}

templates/user/family_details.html
{% extends 'shared/base.html' %}

{% block content %}
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Family Details Form</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/accounts/family.css' %}">
    
</head>
<body>
    <div class="container ">
        <div class="image-container">
            <img src="{% static 'assets/img/userimg/cple1.jpg'%}" alt="Image">
        </div>
        
        <div class="login-container">
            <ul class="progressbar">
                <li class="active">Step 1</li>
                <li class="active">Step 2</li>
                <li >Step 3</li>
                <li>Step 4</li>
                <li>Step 5</li>
                <li>Step 6</li>
            </ul>
            <h2 class="mb-2 text-center mt-4">Family Details</h2>
            <form method="POST" action="{% url 'app:family_details'%}">
                {% csrf_token %}
                <div class="row">
                    <div class="col">
                        {% include 'components/form_field.html' with field=form.father_name %}
                    </div>
                    <div class="col">
                        {% include 'components/form_field.html' with field=form.father_occupation %}
                    </div>
                </div>
              
                <div class="row">
                    <div class="col">
                        {% include 'components/form_field.html' with field=form.mother_name %}
                    </div>
                    <div class="col">
                        {% include 'components/form_field.html' with field=form.mother_occupation %}
                    </div>
                </div>
              
                <div class="row">
                    <div class="col">
                        {% include 'components/form_field.html' with field=form.num_of_siblings %}
                    </div>
                    <div class="col">
                        {% include 'components/form_field.html' with field=form.marital_status %}
                    </div>
                </div>
              
                <div class="row">
                    <div class="col">
                        {% include 'components/form_field.html' with field=form.religion %}
                    </div>
                    <div class="col">
                        {% include 'components/form_field.html' with field=form.caste %}
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        {% include 'components/form_field.html' with field=form.family_values %}
                    </div>
                    <div class="col">
                        {% include 'components/form_field.html' with field=form.disability %}
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        {% include 'components/form_field.html' with field=form.family_type %}
                    </div>
                    <div class="col">
                        {% include 'components/form_field.html' with field=form.family_class %}
                    </div>
                </div>
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                        Next <i class="fas fa-arrow-right"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
{% endblock content %}

templates/user/partner.html
{% extends 'shared/base.html' %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Additional Details and Partner Preferences</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <style>
        .container-box {
            box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15);
            padding: 20px;
            background-color: #f8f9fa;
            border-radius: 8px;
        }
        .form-container {
            box-shadow: 0 0.25rem 0.75rem rgba(0, 0, 0, 0.1);
            padding: 15px;
            background-color: #ffffff;
            border-radius: 8px;
        }
    </style>
</head>
<body>
    <div class="container mt-5 container-box">
        <div class="form-container">
            <h2 class="mb-4">Additional Details</h2>
            <form method="POST" action="{% url 'app:partner' %}">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        {% include 'components/form_field.html' with field=form.height %}
                    </div>
                    <div class="form-group col-md-6">
                        {% include 'components/form_field.html' with field=form.weight %}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        {% include 'components/form_field.html' with field=form.income %}
                    </div>
                    <div class="form-group col-md-6">
                        {% include 'components/form_field.html' with field=form.horoscope %}
                    </div>
                </div>

                <h2 class="mb-4 mt-5">Partner Preferences</h2>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        {% include 'components/form_field.html' with field=form.from_height %}
                    </div>
                    <div class="form-group col-md-6">
                        {% include 'components/form_field.html' with field=form.to_height %}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        {% include 'components/form_field.html' with field=form.from_age %}
                    </div>
                    <div class="form-group col-md-6">
                        {% include 'components/form_field.html' with field=form.to_age %}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        {% include 'components/form_field.html' with field=form.from_weight %}
                    </div>
                    <div class="form-group col-md-6">
                        {% include 'components/form_field.html' with field=form.to_weight %}
                    </div>
                </div>
                <div class="form-group">
                    {% include 'components/form_field.html' with field=form.caste %}
                </div>
                <div class="form-group">
                    {% include 'components/form_field.html' with field=form.religion %}
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        {% include 'components/form_field.html' with field=form.min_income %}
                    </div>
                    <div class="form-group col-md-6">
                        {% include 'components/form_field.html' with field=form.max_income %}
                    </div>
                </div>
                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">Next<i class="fas fa-arrow-right"></button>
                </div>
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#caste').select2({
                placeholder: "Select Caste"
            });
            $('#religion').select2({
                placeholder: "Select Religion"
            });
        });
    </script>
</body>
</html>
{% endblock content %}

templates/user/view.html
{% extends 'shared/base.html' %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile View</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .profile-picture {
            max-width: 150px;
            max-height: 200px;
            border-radius: 20%;
            object-fit: cover;
        }
        
        .edit-button {
            text-align: right;
        }

        /* Styling for containers */
        .section-container {
            margin-bottom: 20px;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
            background-color: #ffffff;
        }
        
    </style>
</head>
<body>
   

    <div class="container mt-5">
        
        <div class="card">
            <div class="card-header">
                <h1>Profile View and Edit</h1>
            </div>
            <div class="card-body">
                <div class="row mb-4">
                    <div class="col-md-2">
                        <img src="{{ data.profile_photo.url }}" alt="Profile Picture" class="profile-picture">
                    </div>
                    <div class="col-md-10 d-flex align-items-center">
                        <div class='row'>
                        <form action="{% url 'app:change_profile'%}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="profile_photo">Change Profile Picture:</label>
                                <input type="file" class="form-control-file" id="profile_photo" name="profile_photo">
                            </div>
                            <button type="submit" class="btn btn-primary">Upload</button>
                        </form>
                    </div>
                    <div class='row' >
                        <h5>Upload Multiple Images and Reels</h5>
                        <a class="btn btn-primary" href="{% url 'app:upload_files'%}" role="tab" aria-controls="partner-details" aria-selected="false">Upload Images and Reels</a>
                    </div>
                    </div>
                </div>
                
                <!-- Basic Details -->
                <section id="basic-details" class="section-container">
                    <h2>Basic Details</h2>
                    <div class="edit-button">
                        <a href="{% url 'accounts:profile_edit' %}" class="btn btn-primary">Edit Profile</a>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>First Name: </strong> {{ data.first_name }}</p>
                            <p><strong>Last Name:</strong> {{ data.last_name }}</p>
                            <p><strong>Username:</strong> {{ data.username }}</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>Email:</strong> {{ data.email }}</p>
                            <p><strong>Phone Number:</strong> {{ data.phone_number }}</p>
                            <p><strong>Date of Birth:</strong> {{ data.date_of_birth }}</p>
                        </div>
                    </div>
                </section>

                <!-- Additional Details -->
                <section id="additional-details" class="section-container">
                    <h2>Additional Details</h2>
                    <div class="edit-button">
                        <a href="{% url 'accounts:additional_edit' %}" class="btn btn-primary">Edit Profile</a>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Hobbies:</strong> {{ data.hobbies }}</p>
                            <p><strong>Gender:</strong> {{ data.gender }}</p>
                            <p><strong>Interest:</strong> {{ data.interest }}</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>Smoking Habits:</strong> {{ data.smoking_habits }}</p>
                            <p><strong>Drinking Habits:</strong> {{ data.drinking_habits }}</p>
                            <p><strong>Qualification:</strong> {{ data.qualification }}</p>
                        </div>
                    </div>
                </section>

                <!-- Address Details -->
                <section id="address-details" class="section-container">
                    <h2>Address Details</h2>
                    <div class="edit-button">
                        <a href="{% url 'accounts:address_edit' %}" class="btn btn-primary">Edit Profile</a>
                    </div>
                    {% for address in addresses %}
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <p><strong>Address Line1:</strong> {{ address.address_line1 }}</p>
                            <p><strong>Address Line2:</strong> {{ address.address_line2 }}</p>
                            <p><strong>City:</strong> {{ address.city }}</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>State:</strong> {{ address.state }}</p>
                            <p><strong>Zip Code:</strong> {{ address.zipcode }}</p>
                            <p><strong>Country:</strong> {{ address.country }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </section>


                <!-- Employment Details -->
                <section id="employment-details" class="section-container">
                    <h2>Employment Details</h2>
                    <div class="edit-button">
                        <a href="{% url 'accounts:employ_edit' %}" class="btn btn-primary">Edit Profile</a>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Job Status:</strong> {{ data.job_status }}</p>
                            <p><strong>Company Name:</strong> {{ data.company_name }}</p>
                            <p><strong>Job Title:</strong> {{ data.job_title }}</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>Designation:</strong> {{ data.designation }}</p>
                            <p><strong>Company Location:</strong> {{ data.company_location }}</p>
                            <p><strong>Expertise Level:</strong> {{ data.expertise_level }}</p>
                        </div>
                    </div>
                </section>

                <!-- Family Details -->
                <section id="family-details" class="section-container">
                    <h2>Family Details</h2>
                    <div class="edit-button">
                        <a href="" class="btn btn-primary">Edit Profile</a>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Father's Name:</strong> {{ family.father_name }}</p>
                            <p><strong>Father's Occupation:</strong> {{ family.father_occupation }}</p>
                            <p><strong>Siblings:</strong> {{ family.num_of_siblings }}</p>
                            <p><strong>Religion:</strong> {{ family.religion }}</p>
                            <p><strong>Caste:</strong> {{ family.caste }}</p>
                            <p><strong>Family Type:</strong> {{ family.family_type }}</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>Mother's Name:</strong> {{ family.mother_name }}</p>
                            <p><strong>Mother's Occupation:</strong> {{ family.mother_occupation }}</p>
                            <p><strong>Marital Status:</strong> {{ family.marital_status }}</p>
                            <p><strong>Family Values:</strong> {{ family.family_values }}</p>
                            <p><strong>Disability:</strong> {{ family.disability }}</p>
                            <p><strong>Family Class:</strong> {{ family.family_class }}</p>
                        </div>
                    </div>
                </section>

                <!-- Partner Preferences -->
                <section id="partner-preferences" class="section-container">
                    <h2>Partner Preferences</h2>
                    <div class="edit-button">
                        <a href="" class="btn btn-primary">Edit Profile</a>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Your Height:</strong> {{ partner.height }}</p>
                            <p><strong>Your Income:</strong> {{ partner.income }}</p>
                            <hr>
                            <p><strong>Min Height(in cm):</strong> {{ partner.from_height }}</p>
                            <p><strong>Min Weight:</strong> {{ partner.from_weight }}</p>
                            <p><strong>Min Age:</strong> {{ partner.from_age }}</p>
                            <p><strong>Min Income:</strong> {{ partner.min_income }}</p>
                            <p><strong>Religion:</strong> {{ partner.religion }}</p>
                        </div>
                        <div class="col-md-6">
                            <p><strong>Your Weight:</strong> {{ partner.weight }}</p>
                            <p><strong>Horoscope:</strong> {{ partner.horoscope }}</p>
                            <hr>
                            <p><strong>Max Height(in cm):</strong> {{ partner.to_height }}</p>
                            <p><strong>Max Weight:</strong> {{ partner.to_weight }}</p>
                            <p><strong>Max Age:</strong> {{ partner.to_age }}</p>
                            <p><strong>Max Income:</strong> {{ partner.max_income }}</p>
                            <p><strong>Caste:</strong> {{ partner.caste }}</p>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>
{% endblock content %}